const RolesPermissionsLevels = {
  USUARIO: "USUARIO",
  ADICIONAR_USUARIO: "ADICIONAR_USUARIO",
  ALTERAR_USUARIO: "ALTERAR_USUARIO",
  REMOVER_USUARIO: "REMOVER_USUARIO",
  LISTAR_USUARIOS: "LISTAR_USUARIOS",
  CARGOS: "CARGOS",
  ADICIONAR_CARGO: "ADICIONAR_CARGO",
  ALTERAR_CARGO: "ALTERAR_CARGO",
  REMOVER_CARGO: "REMOVER_CARGO",
  LISTAR_CARGO: "LISTAR_CARGO",
};

module.exports = RolesPermissionsLevels;
